### RPM external sherpa 3.0.0
Source: https://gitlab.com/sherpa-team/sherpa/-/archive/v%{realversion}/sherpa-v%{realversion}.tar.gz
Requires: hepmc3 lhapdf blackhat python3 fastjet openmpi recola rivet pythia8 libzip openloops mcfm
BuildRequires: swig

%prep
%setup -q -n sherpa-v%{realversion}

%build
rm -rf build && mkdir build
if [ $OPENLOOPS_ROOT ]; then
  cmake -S . -B build \
    -DCMAKE_INSTALL_PREFIX=%i \
    -DSHERPA_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_Fortran_COMPILER=mpif90 \
    -DSHERPA_ENABLE_ANALYSIS=ON \
    -DSHERPA_ENABLE_EXAMPLES=ON \
    -DSHERPA_ENABLE_INSTALL_LIBZIP=ON \
    -DSHERPA_ENABLE_GZIP=ON \
    -DSHERPA_ENABLE_HEPMC3=ON -DSHERPA_ENABLE_HEPMC3_ROOT=ON -DHEPMC3_DIR=$HEPMC3_ROOT\
    -DSHERPA_ENABLE_INTERNAL_PDFS=OFF \
    -DSHERPA_ENABLE_LHAPDF=ON -DLHAPDF_DIR=$LHAPDF_ROOT\
    -DSHERPA_ENABLE_BLACKHAT=ON -DBLACKHAT_DIR=$BLACKHAT_ROOT \
    -DSHERPA_ENABLE_OPENLOOPS=ON -DOPENLOOPS_DIR=$OPENLOOPS_ROOT \
    -DSHERPA_ENABLE_MCFM=ON -DMCFM_DIR=$MCFM_ROOT \
    -DSHERPA_ENABLE_ROOT=ON -DROOT_DIR=$ROOT_ROOT \
    -DSHERPA_ENABLE_PYTHIA8=ON -DPYHIA8_DIR=$PYTHIA8_ROOT\
    -DSHERPA_ENABLE_RECOLA=ON -DRECOLA_DIR=$RECOLA_ROOT\
    -DSHERPA_ENABLE_RIVET=ON -DRIVET_DIR=$RIVET_ROOT\
    -DSHERPA_ENABLE_PYTHON=ON \
    -DSHERPA_ENABLE_UFO=ON \
    -DSHERPA_ENABLE_THREADING=ON
else
  cmake -S . -B build \
    -DCMAKE_INSTALL_PREFIX=%i \
    -DSHERPA_ENABLE_MPI=ON -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpic++ -DCMAKE_Fortran_COMPILER=mpif90 \
    -DSHERPA_ENABLE_ANALYSIS=ON \
    -DSHERPA_ENABLE_EXAMPLES=ON \
    -DSHERPA_ENABLE_INSTALL_LIBZIP=ON \
    -DSHERPA_ENABLE_GZIP=ON \
    -DSHERPA_ENABLE_HEPMC3=ON -DSHERPA_ENABLE_HEPMC3_ROOT=ON -DHEPMC3_DIR=$HEPMC3_ROOT\
    -DSHERPA_ENABLE_INTERNAL_PDFS=OFF \
    -DSHERPA_ENABLE_LHAPDF=ON -DLHAPDF_DIR=$LHAPDF_ROOT\
    -DSHERPA_ENABLE_BLACKHAT=ON -DBLACKHAT_DIR=$BLACKHAT_ROOT \
    -DSHERPA_ENABLE_OPENLOOPS=OFF \
    -DSHERPA_ENABLE_MCFM=ON -DMCFM_DIR=$MCFM_ROOT \
    -DSHERPA_ENABLE_ROOT=ON -DROOT_DIR=$ROOT_ROOT \
    -DSHERPA_ENABLE_PYTHIA8=ON -DPYHIA8_DIR=$PYTHIA8_ROOT\
    -DSHERPA_ENABLE_RECOLA=ON -DRECOLA_DIR=$RECOLA_ROOT\
    -DSHERPA_ENABLE_RIVET=ON -DRIVET_DIR=$RIVET_ROOT\
    -DSHERPA_ENABLE_PYTHON=ON \
    -DSHERPA_ENABLE_UFO=ON \
    -DSHERPA_ENABLE_THREADING=ON
fi
cmake --build build %{makeprocesses}

%install
cmake --install build
sed -i -e 's|^#!/.*|#!/usr/bin/env python3|' %{i}/bin/Sherpa-generate-model

%post
%{relocateConfig}share/SHERPA-MC/makelibs
%{relocateConfig}bin/Sherpa-config
%{relocateConfig}bin/Sherpa-generate-model
%{relocateConfig}include/SHERPA-MC/ATOOLS/Org/CXXFLAGS*.H
